[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_20"]

[phases.install]
cmds = [
  "npm install"
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan key:generate --force || true",
  "php artisan migrate --force || true",
  "php artisan storage:link || true",
  "php artisan config:clear",
  "php artisan cache:clear",
  "php artisan view:clear",
  "php artisan config:cache",
  "npm run build"
]


[start]
cmd = "php artisan route:clear && php artisan config:clear && php artisan cache:clear && php artisan view:clear && php artisan serve --host=0.0.0.0 --port=$PORT"

